version: '3'
services:
  database:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    ports: [5432:5432]
    volumes:
      - janus-trainer-pgdata:/var/lib/postgresql
volumes:
  janus-trainer-pgdata: {}
