extends:
  - 'next/core-web-vitals'
  - plugin:@next/next/recommended
  - plugin:@typescript-eslint/recommended
plugins:
  - react
  - '@typescript-eslint'
rules:
  '@next/next/no-html-link-for-pages': off
