export const API_COMPENSATIONS = '/api/compensations'
export const API_COMPENSATION_VALUES = '/api/compensation-values'
export const API_COURSES = '/api/courses'
export const API_DISCIPLINES = '/api/disciplines'
export const API_HOLIDAYS = '/api/holidays'
export const API_TRAININGS = '/api/trainings'
export const API_USERS = '/api/users'