env:
  node: true
  jest: true
rules:
  {
    "@typescript-eslint/interface-name-prefix": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-module-boundary-types": "off",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-unused-vars":
      [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
  }
ignorePatterns:
  - dist
  - migrations
  - webpack.config.js
plugins:
- "@typescript-eslint"
extends:
  - plugin:@typescript-eslint/recommended
