service: janus-trainer-backend

# Load environment variables from .env files (default: false)
# See https://www.serverless.com/framework/docs/environment-variables
useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  patterns:
    - dist/main.js
    - .env.production
  #     - dist/src/**
  #     - "!vscode/**"
  #     - "!.yarn/**"
  #     - "!node_modules/.bin/**"
  #     - "!src/**"
  #     - "!test/**"
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  # iam:
  #   # This role will be created by Serverless
  #   role:
  #     statements:
  #       - Effect: Allow

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

custom:
  serverless-offline:
    httpPort: 3001
