on:
  workflow_call:
    inputs:
      deploy-command:
        required: true
        type: string
        description: either deploy:prod or deploy:test
    secrets:
      aws-ecr-key:
        required: true
      aws-ecr-secret-access-key:
        required: true
      postgres-password:
        required: true
jobs:
  deploy-backend-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-ecr-key }}
          aws-secret-access-key: ${{ secrets.aws-ecr-secret-access-key }}
          aws-region: eu-north-1
      - name: yarn install
        run: yarn install
      - name: build dto library
        run: |
          yarn workspace janus-trainer-dto build
      - name: Deploy backend
        env:
          SLS_DEBUG: '*'
          POSTGRES_PASSWORD: ${{ secrets.postgres-password }}
        run: |
          yarn workspace janus-trainer-backend ${{ inputs.deploy-command }}
