on:
  workflow_call: {}

jobs:
  lint-format-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '26.x'
          cache: yarn
      - name: yarn install
        run: yarn install
      - run: |
          yarn prisma generate
      - name: yarn format:check
        run: yarn format:check
      - name: yarn test
        run: yarn test

  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '26.x'
          cache: yarn
      - name: yarn install
        run: yarn install
      - name: Generate Prisma client
        run: yarn prisma generate
      - name: Run API tests
        run: yarn vitest -c api-tests/vite.config.ts
