name: janus-trainer-app
on:
  push:
    branches:
      - main
      - gitlab
  pull_request:
    types: [opened, synchronize]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: yarn install
        run: yarn install
      - name: yarn format
        run: yarn format
      - name: yarn lint
        run: yarn lint
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: docker compose up -d
      - run: yarn install
      - run: yarn build
      - run: yarn start
        env:
          POSTGRES_PASSWORD: postgress
      - run: 'yarn backend migration:run:dev'
      - name: Install Playwright Browsers
        run: yarn e2e playwright install firefox --with-deps
      - name: create env
        id: create-env
        run: |
          echo COGNITO_DOMAIN=https://janus-trainer-dev.auth.eu-north-1.amazoncognito.com/ > packages/janus-trainer-e2e/.env
      - name: Run Playwright tests
        run: yarn e2e playwright:test
        env:
          COGNITO_ADMIN_USERNAME: ${{ vars.COGNITO_ADMIN_USERNAME }}
          COGNITO_ADMIN_PASSWORD: ${{ secrets.COGNITO_ADMIN_PASSWORD }}
          COGNITO_TRAINER_USERNAME: ${{ vars.COGNITO_TRAINER_USERNAME }}
          COGNITO_TRAINER_PASSWORD: ${{ secrets.COGNITO_TRAINER_PASSWORD }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/janus-trainer-e2e/playwright-report/
          retention-days: 1

  frontend-build:
    if: github.ref_name == 'main'
    uses: ./.github/workflows/frontend-build.yaml
    secrets:
      aws-ecr-key: ${{ secrets.AWS_ECR_KEY }}
      aws-ecr-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}

  frontend-deploy-prod:
    if: github.ref_name == 'main'
    needs:
      - frontend-build
      - lint-and-format
    uses: ./.github/workflows/frontend-deploy.yaml
    with:
      image-name: ${{needs.frontend-build.outputs.image-name}}
      function-name: 'arn:aws:lambda:eu-north-1:930650061532:function:janus-trainer-app'
    secrets:
      aws-ecr-key: ${{ secrets.AWS_ECR_KEY }}
      aws-ecr-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}

  deploy-backend-prod:
    if: github.ref_name == 'main'
    needs:
      # the build-frontend has a linting step which does more than eslint.
      # To avoid partial deployments due to aborted frontend builds, we add a dependency
      - frontend-build
      - lint-and-format
    uses: ./.github/workflows/backend-deploy.yaml
    with:
      deploy-command: 'deploy:prod'
    secrets:
      aws-ecr-key: ${{ secrets.AWS_ECR_KEY }}
      aws-ecr-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
      postgres-password: ${{ secrets.POSTGRES_PASSWORD_PROD }}
