on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      function-name:
        required: true
        type: string
    secrets:
      aws-ecr-key:
        required: true
      aws-ecr-secret-access-key:
        required: true
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ inputs.image-name }}
      FUNCTION_NAME: ${{ inputs.function-name }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-ecr-key }}
          aws-secret-access-key: ${{ secrets.aws-ecr-secret-access-key }}
          aws-region: eu-north-1
      - name: Deploy backend image to lambda
        run: |
          aws lambda update-function-code \
            --function-name ${ FUNCTION_NAME } \
            --architectures x86_64 \
            --image-uri ${ IMAGE_NAME }
