on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'The target environment: test, prod, dev'
      domain:
        required: true
        type: string
        description: The domain from which the deployment will be reachable

    secrets:
      aws-ecr-key:
        required: true
      aws-ecr-secret-access-key:
        required: true

env:
  STACK_NAME: janus-trainer-${{ inputs.environment }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-ecr-key }}
          aws-secret-access-key: ${{ secrets.aws-ecr-secret-access-key }}
          aws-region: eu-north-1
      - name: Apply cloudformation template
        run: |
          aws cloudformation deploy \
            --region eu-north-1 \
            --stack-name ${STACK_NAME} \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_NAMED_IAM \
            --template-file ./cloudformation.yaml \
            --parameter-overrides \
                JanusEnvironment=${{inputs.environment}} \
                JanusDomainParameterValue=${{inputs.domain}}
          aws cloudformation wait stack-update-complete --stack-name ${STACK_NAME}
