on:
  workflow_call:
    secrets:
      aws-ecr-key:
        required: true
      aws-ecr-secret-access-key:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.push.outputs.image-name }}
    steps:
      - uses: actions/checkout@v6
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-ecr-key }}
          aws-secret-access-key: ${{ secrets.aws-ecr-secret-access-key }}
          aws-region: eu-north-1
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/janus/janus-trainer:${{ github.run_id }}
