on:
  workflow_call:
    secrets:
      cognito-admin-password:
        required: true
      cognito-trainer-password:
        required: true
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: yarn
      - run: yarn install
      - run: yarn start:dev &
      - name: Install Playwright Browsers
        run: yarn playwright install firefox --with-deps
      - name: Remove .env for tests
        run: rm -f playwright/.env
      - name: Run Playwright tests
        run: yarn playwright:test
        env:
          PLAYWRIGHT_BASE_URL: 'https://janus-test.lippert.dev'
          COGNITO_ADMIN_USERNAME: janus.test.admin@fastmail.com
          COGNITO_ADMIN_PASSWORD: ${{ secrets.cognito-admin-password }}
          COGNITO_TRAINER_USERNAME: janus.test.trainer.1@fastmail.com
          COGNITO_TRAINER_PASSWORD: ${{ secrets.cognito-trainer-password }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright/test-report/
          retention-days: 1
